services:
  app:
    image: hello-front-dev
    build: 
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    container_name: hello-front-dev
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-todo-app
    depends_on:
      - app
